[package]
name = "sysinfo-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = { version = "0.23.10", default-features=false }
fltk = "1.3"
lazy_static = "1.4"
crossbeam-channel = "0.5"

[profile.release]
opt-level = 3
strip = true