[package]
name = "sysinfo-gui"
version = "0.1.2"
edition = "2021"
repository = "https://github.com/MoAlyousef/sysinfo-gui"
keywords = ["cross-platform", "monitoring", "gui"]
license = "MIT"
categories = ["visualization"]
description = "A cross-platform system-monitoring gui application based on sysinfo and fltk"
documentation = "https://doc.rs/sysinfo-gui"
readme = "README.md"

[dependencies]
sysinfo = { version = "0.23.10", default-features=false }
fltk = "1.3"
fltk-grid = "0.1"
parking_lot = "0.12"

[profile.release]
opt-level = 3
strip = true