name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-10.15, ubuntu-18.04]
    
    steps:
    - name: Download deps
      run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update && sudo apt-get install -y libpango-1.0-0 libx11 libxext libxft libxinerama libxcursor libxrender libxfixes
         fi
      shell: bash
    - uses: actions/checkout@v2
    - name: Build
      shell: bash
      run: cargo build --release --features=fltk/fltk-bundled
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sysinfo-gui
        path: target/release/sysinfo-gui
