name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-10.15, ubuntu-18.04]
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      shell: bash
      run: cargo build --release --features=fltk/fltk-bundled
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sysinfo-gui
        path: target/release/sysinfo-gui
